OPENAI_API_KEY : ""
WHISPER_URL : "http://localhost:10000"
NEMO_URL : "http://localhost:10000"
WEBRTC_AUDIO_BUFFER_SIZE : 4096
TMP_AUDIO_BUFFER_LENGTH: 5000 # 3 seconds
SESSION_AUDIO_BUFFER_LENGTH : 60000 # 60 seconds
API_KEY: ""
HOTWORD_DETECTION_INTERVAL_MS: 1000 # 1 second

PYDUB_MIN_SILENCE_LEN: 1000 # 1 second
PYDUB_SILENCE_THRESHOLD: -40
CHATGPT_CONTEXT_LENGTH: 5
CHATGPT_MAX_TOKENS: 500